# Generated by Django 2.1 on 2018-09-11 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ourworks', '0002_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
